ddvug_willibald_samen:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: "{{ env_var('DBT_DATABASE') }}"
      warehouse: compute_wh
      schema: PUBLIC
      threads: 4